[tool.ruff]
# Specify the target Python version for compatibility checks.
target-version = "py310"

# Select which linting rules to enable.
# 'E' and 'F' are standard Flake8 rules.
# Extend with other common rule sets like 'I' (isort), 'UP' (pyupgrade), etc.
select = ["E", "F", "I", "UP", "B", "C4", "N", "D", "ANN"]

# Ignore specific rules for the entire project.
# This is useful for rules that might not apply or are intentionally bypassed.
ignore = ["E501", "D100"] # Example: Ignore line length and missing module docstring

# Exclude files or directories from linting.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Configure line length for formatting.
line-length = 88

# Enable automatic fixing of fixable issues.
fix = true

[tool.ruff.per-file-ignores]
# Ignore specific rules for certain files or patterns.
"tests/*.py" = ["D"] # Ignore docstring rules in test files
"docs/*.py" = ["D"] # Ignore docstring rules in documentation files

[tool.ruff.isort]
# Configure isort-specific settings.
known-first-party = ["my_package"] # List of your project's top-level packages
force-single-line = false

[tool.ruff.format]
# Configure formatting settings.
quote-style = "double"
indent-style = "space"
line-ending = "auto"
