"""Download engine implementations."""

from .base import BaseDownloadEngine
from .http_ftp_engine import HttpFtpEngine
from .media_engine import MediaEngine
from .media_models import (
    AuthConfig as MediaAuthConfig,
)
from .media_models import (
    AuthMethod as MediaAuthMethod,
)
from .media_models import (
    BatchDownloadConfig,
    BatchProgress,
    ChapterInfo,
    FormatPreferences,
    MediaConfig,
    MediaFormat,
    MediaInfo,
    MediaMetadata,
    PlaylistInfo,
    ProcessingResult,
    ProcessingStep,
    SubtitleInfo,
)
from .media_models import (
    DownloadProgress as MediaDownloadProgress,
)
from .media_models import (
    DownloadStatus as MediaDownloadStatus,
)
from .pycurl_models import (
    AuthConfig,
    AuthMethod,
    CompletedSegment,
    CurlError,
    DownloadSegment,
    ErrorAction,
    ErrorCategory,
    HttpFtpConfig,
    ProxyConfig,
    ProxyType,
    SegmentMergeInfo,
    SegmentStatus,
    SshConfig,
    WorkerProgress,
    WorkerStatus,
)
from .registry import (
    EngineRegistry,
    detect_engine_for_url,
    get_engine_for_url,
    get_registry,
    initialize_default_engines,
)
from .segment_merger import SegmentMerger
from .torrent_engine import TorrentEngine
from .torrent_models import (
    AlertCategory,
    AlertSeverity,
    AlertType,
    AllocationMode,
    ChokingAlgorithm,
    ConnectionType,
    EncryptionPolicy,
    FilePriority,
    FileProgress,
    PeerFlag,
    PeerInfo,
    SessionStats,
    SwarmHealth,
    TorrentAlert,
    TorrentConfig,
    TorrentFile,
    TorrentInfo,
    TorrentState,
    TorrentStatus,
    TrackerInfo,
    TrackerStatus,
)

__all__ = [
    "AlertCategory",
    "AlertSeverity",
    "AlertType",
    "AllocationMode",
    "AuthConfig",
    "AuthMethod",
    "BaseDownloadEngine",
    "BatchDownloadConfig",
    "BatchProgress",
    "ChapterInfo",
    "ChokingAlgorithm",
    "CompletedSegment",
    "ConnectionType",
    "CurlError",
    "DownloadSegment",
    "EncryptionPolicy",
    "EngineRegistry",
    "ErrorAction",
    "ErrorCategory",
    "FilePriority",
    "FileProgress",
    "FormatPreferences",
    "HttpFtpConfig",
    "HttpFtpEngine",
    "MediaAuthConfig",
    "MediaAuthMethod",
    "MediaConfig",
    "MediaDownloadProgress",
    "MediaDownloadStatus",
    "MediaEngine",
    "MediaFormat",
    "MediaInfo",
    "MediaMetadata",
    "PeerFlag",
    "PeerInfo",
    "PlaylistInfo",
    "ProcessingResult",
    "ProcessingStep",
    "ProxyConfig",
    "ProxyType",
    "SegmentMergeInfo",
    "SegmentMerger",
    "SegmentStatus",
    "SessionStats",
    "SshConfig",
    "SubtitleInfo",
    "SwarmHealth",
    "TorrentAlert",
    "TorrentConfig",
    "TorrentEngine",
    "TorrentFile",
    "TorrentInfo",
    "TorrentState",
    "TorrentStatus",
    "TrackerInfo",
    "TrackerStatus",
    "WorkerProgress",
    "WorkerStatus",
    "detect_engine_for_url",
    "get_engine_for_url",
    "get_registry",
    "initialize_default_engines",
]
